### ISSUE TITLE
[BUG] Canvas containing images disappears when launching Obsidian

### ISSUE THREAD

**Issue by ergbennett** [Developer-Mike/obsidian-advanced-canvas#190]
A week or so ago, I updated to whichever version came right before 3.10.0. After that, I noticed that my canvases that had images on them would get completely wiped whenever I opened them, and whenever I launched Obsidian with that canvas being open from a previous session. Wiped, as in, the text file reverts to a blank canvas. Canvases with note embeds or text cards don't seem to do this. I can use the version history to get the canvas back, but it just gets wiped again the next time I open it after closing and re-opening Obsidian.

This bug doesn't occur when closing and re-opening the canvas in the same session in Obsidian--only after closing and re-opening Obsidian. 

https://github.com/user-attachments/assets/717c87fa-7387-4fa7-958b-36b4feb0868a

I have the following plug-ins enabled:

Advanced Canvas
Auto Note Mover
Better Word Count
Book Search
Canvas Mindmap
Dataview
Excalidraw
Find orphaned files and broken links
Image Captions
Janitor
Journey
JSON/CSV Importer
Keep the Rhythm
Lineage
Media Notes
Meta Bind
MOC Link Helper
Modal forms
Multi Properties
Note Refactor
Omnisearch
Outliner
Projects
Prompt
QuickAdd
Quiz Generator
Sort & Permute lines
Spaced Repetition
Style Settings
Tag Wrangler
Tasks
Templater
Text Extractor
Update time on edit
Writing Goals

**Comment by Developer-Mike** [comment]
Does this issue still occur in version 3.10.0?

And can you tell me if the file really gets wiped or just doesn't display properly after the first open?

**Comment by ergbennett** [comment]
I updated to 3.10.0 today, before reporting the bug, and the issue still occurs. The first time it happened, I checked the .canvas file in Windows explorer, and all of my data was gone.

**Comment by Developer-Mike** [comment]
And is there any error in the console (`Ctrl + Shift + I`)?

**Comment by ergbennett** [comment]
This is all that's left in the .canvas file: 
```
{
  "edges": [
  ],
  "nodes": [
  ]
}
```

This is the only issue message in the console after launching Obsidian:

![Image](https://github.com/user-attachments/assets/51c6a6e9-8f03-495f-a831-8a636dc235ee)

**Comment by Developer-Mike** [comment]
@phanquanghung What plugins do you use?
@ergbennett @phanquanghung What version of Obsidian do you use and does it still occur if you only have Advanced Canvas enabled?

**Comment by pauldorman** [comment]
Happens to me. Once before I turned on automatic Git backups unfortunately. Lost about 12 hours of work.

Obsidian version 1.8.9
Advanced Canvas version currently 3.10.0

Other plugins:
Advanced Slides
Calendar
CardBoard
Dataview
Excalidraw
Git
Highlightr
Hot Reload
Iconize
Kanban
Outliner
PlantUML
Style Settings
Tasks
Templater

All are up to date.

The absolute worst kind of bug is one which deletes your data. I wish you well with squashing it!

**Comment by Developer-Mike** [comment]
It may have got introduced in version `3.9.1`. I've pushed a fix that hopefully resolves this issue. Please 
let me know immediately, if this issue occurs in version `3.10.1`.

@pauldorman Obsidian has a "File Recovery" core plugin. Please check if you have any snapshots there (If it's not too late already)

**Comment by pauldorman** [comment]
Thanks @Developer-Mike, too late, yes :). Restoring from Git works fine for me, so no more lost work.

**Comment by ergbennett** [comment]
I've updated to 3.10.1 and the issue still occurs. I created a new vault with some core plugins and Advanced Canvas, with no other community plugins. Sometimes its fine if I use new attachments from my Windows file explorer, but sometimes it isn't, and I haven't been able to find a pattern.

**Comment by pauldorman** [comment]
I concur with @ergbennett. Just happened to me again. I made sure I committed all my changes before I closed Obsidian though :)

**Comment by Developer-Mike** [comment]
Can you send me the console output (you need to set logging to all levels on the top right (enable verbose)). It would help a lot. Should look something like this: Reloading canvas view (Saving: ___)

**Comment by Developer-Mike** [comment]
> At a guess I'd say it's probably something to do with the "Reloading canvas view (Saving: false)" message.
Yes, definitely. This change was made in version `3.9.1` to fix #173. But there is absolutely no reason that this would fail like this. There is a 100% (apparently not) foolproof is-saved check. I will take a look at it today and revert changes made for #173 if I can't find a solution.

> Just want to say thanks for jumping on this so fast. Thanks!
No problem, this is definitely a big issue! So no time to loose 😅

**Comment by Developer-Mike** [comment]
In version `3.10.2` I've rewrote a good chunk of patching logic. This issue is definitely fixed!

**Comment by pauldorman** [comment]
Seems fixed to me! 🎉 

I did a few restarts with various Canvas pages open and they were restored without issue.

Thanks, @Developer-Mike!

**Comment by ergbennett** [comment]
I opened and closed Obsidian a few times with active canvases containing images, and everything seems fine. Thank you so much for your hard work and the quick turnaround. 🏆🥳🎉
