### ISSUE TITLE
[BUG] Invalid JSON when .canvas file gets created using the add file node command

### ISSUE THREAD

**Issue by Divedivine** [Developer-Mike/obsidian-advanced-canvas#38]
<img width="290" alt="Skärmavbild 2024-03-22 kl  20 51 54" src="https://github.com/Developer-Mike/obsidian-advanced-canvas/assets/164561205/265e6675-d940-4a06-a687-40ef330f3ecd">
What is this, a bug?

Anyone know how to get around?
I've tried to reinstall both Obsidian as well as plugins etc when I deactivate Advanced Canvas it works but as soon as I activate it again I cant make a new Canvas only work in those already created?

Mac M1

**Comment by kulizivo** [comment]
I have a similar problem and still haven't found a work around outside of turning off the plugin

**Comment by Divedivine** [comment]
Noone else with this Prob?

**Comment by Developer-Mike** [comment]
Thank you so much for this critical bug report 🙏🏻. It got fixed in the version `2.7.2` (This bug was due to changes made in version `2.7.0`)

**Comment by Divedivine** [comment]
I did the update but the same problem remains?
Is there something I missed?

**Comment by Developer-Mike** [comment]
It's working for me... How do you create your canvas (e.g. Through the command)? And make sure, you have version `2.7.2` installed.

**Comment by Developer-Mike** [comment]
Just found the issue! Fixed in version `2.7.3`

**Comment by Divedivine** [comment]
Yeeees!!!
Now it works again. Awesome!

**Comment by jeansordes** [comment]
@Developer-Mike I've just installed this plugin and I have the same issue, I'm using version 3.0.4 🤔

**Comment by Developer-Mike** [comment]
You're right. It will be fixed in the next version.

**Comment by Developer-Mike** [comment]
Fixed in version `3.0.5`
